[tool.poetry]
name = "task-2"
version = "0.1.0"
description = "lms personal bot"
authors = ["MARVRK"]
license = "NONE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
