[tool.poetry]
name = "hm4"
version = "1.0"
description = "hm4"
authors = ["MARVRK"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
