# Generated by Django 5.0.6 on 2024-05-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_delete_quotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='authors',
            new_name='author',
        ),
    ]
